//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int Id { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> billDate { get; set; }
    }
}
