//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PharmacyEntity : DbContext
    {
        public PharmacyEntity()
            : base("name=PharmacyEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pharmacist> pharmacists { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<account> accounts { get; set; }
    }
}
